### ISSUE TITLE
Add some usage examples

### ISSUE THREAD

**Issue by bitick** [ntex-rs/ntex-amqp#3]
Hello, I’m very interested in your crate, but cannot get a simple client working. 

Can you provide some examples, or maybe howtos how to work with your framework?

I’m very newbie to rust and actix at all, but want to play with it and maybe can I do some help?

**Comment by ctron** [comment]
Same here. I am super curious about this client, but after spending a few hours I am still missing the basics.

**Comment by jocutajar** [comment]
Let's work it out! :D https://stackoverflow.com/questions/68080491/rust-receive-amqp-messages-from-azure-event-hub
