### ISSUE TITLE
examples and documentation to use the crate

### ISSUE THREAD

**Issue by abdelmonem17** [ntex-rs/ntex-amqp#6]
Can you provide documentation for the crate and examples to create a client for sending and receiving messages

**Comment by fafhrd91** [comment]
there are two examples in examples directory. and you can check api docs. better docs would be helpful, i would gladly accept PR with better docs.

**Comment by abdelmonem17** [comment]
thank you for help but it is very simple example and doesn't show how to use library feature like sending and receiving.

**Comment by fafhrd91** [comment]
check api docs
