### ISSUE TITLE
fail to make client to connect to ActiveMq broker

### ISSUE THREAD

**Issue by abdelmonem17** [ntex-rs/ntex-amqp#7]
fail to make client to connect to ActiveMq broker throw AMQP 1.0 I use the following example
but it give me run time exception for connection result
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Resolver(ResolveError { kind: NoRecordsFound { query: Query { name: Name { is_fqdn: false, labels: [ampq] }, query_type: AAAA, query_class: IN }, valid_until: Some(Instant { t: 389237.4048147s }) }, backtrack: None }))', src\main.rs:12:10
stack backtrace:
and in activemq log it gives me that 
WARN | Transport Connection to: tcp://127.0.0.1:57964 failed: org.apache.activemq.transport.amqp.AmqpProtocolException: Connection from client using unsupported AMQP attempted

```
use ntex_amqp::client;

#[ntex::main]
async fn main() -> std::io::Result<()> {
    std::env::set_var("RUST_LOG", "ntex=trace,ntex_amqp=trace,basic=trace");


    let driver = client::Connector::new()
        .connect("ampq://127.0.0.1:5672")
        .await
        .unwrap();
    let sink = driver.sink();

    ntex::rt::spawn(driver.start_default());

    let _session = sink.open_session().await.unwrap();

    Ok(())
}
```

**Comment by fafhrd91** [comment]
try .connect("127.0.0.1:5672")
